export const defaultAdmin = {
  name: 'Ashok Yadav',
  email: 'admin@parasproperty.com',
  password: 'admin123',
  role: 'admin',
};

export const defaultSettings = {
  key: 'general',
  companyName: 'Paras Property',
  tagline: 'Verified Plots & Premium Properties in Prime Locations',
  ownerName: 'Ashok Yadav & Adv. Balbir Singh',
  ownerRole: 'Property & Legal Advisors',
  ownerPhoto: '/images/ashok-yadav.jpg',
  ownerMessage: 'With over a decade of hands-on experience in prime residential plots, commercial lands, and gated townships across Jaipur, our personal commitment at Paras Property is to ensure 100% legal title verification, direct developer pricing, and a smooth registry experience for every buyer.',
  phone: '+91 77426 50820',
  whatsapp: '7742650820',
  email: 'contact@parasproperty.com',
  address: 'Tonk Road, Near Airport, Jaipur, Rajasthan 302018',
  metaPixelId: '',
  currencySymbol: '₹',
  facebookUrl: 'https://facebook.com',
  instagramUrl: 'https://instagram.com',
  youtubeUrl: 'https://youtube.com',
};

export const initialProperties = [
  {
    title: 'Grand Vista 1200 Sq Ft Gated Township Plot',
    slug: 'grand-vista-1200-sq-ft-gated-township-plot',
    propertyType: 'Residential Plot',
    location: 'Jagatpura, Jaipur',
    address: 'Sector 9, Jagatpura Extension, Jaipur, Rajasthan',
    price: 4200000,
    priceUnit: 'Lakh',
    priceDisplay: '₹42 Lakh',
    size: 1200,
    sizeUnit: 'sq ft',
    facing: 'North-East',
    roadWidth: '40 ft Wide Sector Road',
    status: 'Available',
    isFeatured: true,
    description: `A pristine residential plot located inside an ultra-secure 50-acre gated township near Jagatpura railway station and upcoming metro corridor. Featuring underground electrification, wide bitumen roads, landscaped central park, and clubhouse.

Immediate registry with 80% bank loan approval from SBI and HDFC Bank. Ideal for building a luxury 3-story independent villa or long-term high capital appreciation investment.`,
    legalInformation: ['JDA Approved', 'RERA Registered', 'Freehold Title', 'Bank Loan Available (SBI/HDFC)', 'Immediate Registry'],
    amenities: [
      'Gated Security & CCTV Surveillance',
      '40 ft Wide Tar Roads',
      'Underground Electrical Cabling',
      'Landscaped Green Parks & Jogging Track',
      '24/7 Water Supply Connection',
      'Modern Drainage & Sewerage Lines',
      'Clubhouse & Children Play Area',
      'Street Light Infrastructure'
    ],
    nearbyLandmarks: [
      'Jaipur International Airport - 12 mins',
      'Jagatpura Railway Station - 6 mins',
      'Bombay Hospital - 8 mins',
      'Mahatma Gandhi University & Hospital - 10 mins',
      'Decathlon & D-Mart - 5 mins'
    ],
    latitude: 26.8289,
    longitude: 75.8617,
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    videoTitle: 'Gated Township Walkthrough & Drone View',
    images: [
      {
        url: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=1600&q=80',
        altText: 'Township Plot Layout View',
        displayOrder: 0,
        isCover: true,
      },
      {
        url: 'https://images.unsplash.com/photo-1592595896551-12b371d546d5?auto=format&fit=crop&w=1600&q=80',
        altText: 'Township Gated Entrance Gate',
        displayOrder: 1,
        isCover: false,
      },
      {
        url: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1600&q=80',
        altText: 'Sample Villa Architecture Plan',
        displayOrder: 2,
        isCover: false,
      },
      {
        url: 'https://images.unsplash.com/photo-1513836279014-a89f7a76ae86?auto=format&fit=crop&w=1600&q=80',
        altText: 'Landscaped Park and Pathways',
        displayOrder: 3,
        isCover: false,
      },
    ],
  },
  {
    title: 'Emerald Corner 200 Sq Yard Villa Plot',
    slug: 'emerald-corner-200-sq-yard-villa-plot',
    propertyType: 'Plot',
    location: 'Ajmer Road, Jaipur',
    address: 'Near Omaxe City, Ajmer Express Highway, Jaipur',
    price: 3600000,
    priceUnit: 'Lakh',
    priceDisplay: '₹36 Lakh',
    size: 1800,
    sizeUnit: 'sq ft',
    facing: 'East Facing',
    roadWidth: '60 ft Main Road',
    status: 'Available',
    isFeatured: true,
    description: `Prime corner residential plot with dual 60ft and 40ft road frontage. Situated in a rapidly developing luxury corridor on Ajmer Road near prominent international schools and IT SEZ (Mahindra World City).

The plot offers excellent sunlight orientation, vastu compliance, and high rental and resale demand due to booming corporate employment hubs nearby.`,
    legalInformation: ['Approved Layout', '100% Clear Title', 'Ready Possession', 'Bank Finance Ready'],
    amenities: [
      'Corner Plot Advantage (Dual Road Frontage)',
      '60 ft Main Sector Boulevard',
      'Rainwater Harvesting System',
      'Overhead Water Tank & Supply',
      'Perimeter Wall & Security Booth',
      'Solar Powered Street Illumination'
    ],
    nearbyLandmarks: [
      'Mahindra World City SEZ - 7 mins',
      'DPS International School - 4 mins',
      'Manipal University - 12 mins',
      'Ajmer Express Highway - 2 mins'
    ],
    latitude: 26.8524,
    longitude: 75.6874,
    videoUrl: '',
    images: [
      {
        url: 'https://images.unsplash.com/photo-1576013551627-0cc20b96c2a7?auto=format&fit=crop&w=1600&q=80',
        altText: 'Emerald Corner Plot View',
        displayOrder: 0,
        isCover: true,
      },
      {
        url: 'https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=1600&q=80',
        altText: 'Surrounding Green Corridor',
        displayOrder: 1,
        isCover: false,
      },
      {
        url: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=1600&q=80',
        altText: 'Township Infrastructure',
        displayOrder: 2,
        isCover: false,
      },
    ],
  },
  {
    title: 'Highway Touch Commercial Showroom Plot',
    slug: 'highway-touch-commercial-showroom-plot',
    propertyType: 'Commercial Plot',
    location: 'Tonk Road, Jaipur',
    address: 'Main Tonk Road Highway, Near Chokhi Dhani, Jaipur',
    price: 11500000,
    priceUnit: 'Crore',
    priceDisplay: '₹1.15 Crore',
    size: 2700,
    sizeUnit: 'sq ft',
    facing: 'North Facing',
    roadWidth: '100 ft National Highway Frontage',
    status: 'Available',
    isFeatured: true,
    description: `High-visibility commercial plot directly fronting the 100ft National Highway corridor on Tonk Road. Unmatched footfall and vehicular traffic exposure, ideal for multi-brand automobile showrooms, retail outlets, banks, diagnostic centers, or corporate headquarters.

Commercial zoning permission granted with maximum FAR floor allowance. Heavy rental yields with prominent corporate tenants seeking roadside commercial spaces.`,
    legalInformation: ['Commercial Conversion Approved', 'Commercial NOC in hand', 'Clear Encumbrance Certificate', 'Direct Highway Access'],
    amenities: [
      '100 ft Direct Highway Frontage',
      'Heavy Vehicular Traffic Exposure',
      'High FAR Allowance (G+4 Ready)',
      'Dedicated Commercial Transformer Connection',
      'Ample Roadside Customer Parking Space',
      'High-Speed Optical Fiber Connectivity'
    ],
    nearbyLandmarks: [
      'Jaipur International Airport - 8 mins',
      'Chokhi Dhani Resort - 3 mins',
      'Sitapura Industrial Area - 5 mins',
      'Apex University Campus - 6 mins'
    ],
    latitude: 26.7923,
    longitude: 75.8274,
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    videoTitle: 'Highway Commercial Frontage Drone Footage',
    images: [
      {
        url: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1600&q=80',
        altText: 'Highway Frontage Commercial Hub',
        displayOrder: 0,
        isCover: true,
      },
      {
        url: 'https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=1600&q=80',
        altText: 'Modern Commercial Building Architecture',
        displayOrder: 1,
        isCover: false,
      },
    ],
  },
  {
    title: 'Luxury 4 BHK Designer Villa with Private Garden',
    slug: 'luxury-4-bhk-designer-villa-with-private-garden',
    propertyType: 'Villa',
    location: 'Mansarovar Extension, Jaipur',
    address: 'Near Muhana Mandi Road, Mansarovar Ext, Jaipur',
    price: 8500000,
    priceUnit: 'Lakh',
    priceDisplay: '₹85 Lakh',
    size: 2400,
    sizeUnit: 'sq ft',
    facing: 'North Facing',
    roadWidth: '40 ft Sector Road',
    status: 'Reserved',
    isFeatured: false,
    description: `Brand new ready-to-move 4 BHK ultra-luxury duplex villa with Italian marble flooring, false ceiling with ambient LED cove lighting, modular kitchen with chimney & hob, and landscaped rooftop garden terrace.

Equipped with covered 2-car porch, home automation switches, branded Jaquar sanitary fittings, and separate servant room with bath.`,
    legalInformation: ['JDA Approved', 'Freehold Title', 'Registry Ready', 'Bank Loan Available up to 85%'],
    amenities: [
      '2-Car Covered Porch',
      'Private Landscaped Lawn & Rooftop Garden',
      'Italian Marble & Wooden Textured Flooring',
      'Smart Home Video Door Phone',
      'Gourmet Kitchen with Quartz Countertops',
      'Solar Rooftop Geyser Ready'
    ],
    nearbyLandmarks: [
      'Mansarovar Metro Station - 10 mins',
      'St. Wilfred College - 5 mins',
      'Muhana Mandi - 4 mins',
      'City Park Mansarovar - 8 mins'
    ],
    latitude: 26.8378,
    longitude: 75.7612,
    videoUrl: '',
    images: [
      {
        url: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=1600&q=80',
        altText: 'Villa Front Elevation',
        displayOrder: 0,
        isCover: true,
      },
      {
        url: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1600&q=80',
        altText: 'Spacious Designer Living Hall',
        displayOrder: 1,
        isCover: false,
      },
      {
        url: 'https://images.unsplash.com/photo-1600566753376-12c8ab7fb75b?auto=format&fit=crop&w=1600&q=80',
        altText: 'Modular Chef Kitchen',
        displayOrder: 2,
        isCover: false,
      },
    ],
  },
  {
    title: 'Serene Green 1-Acre Farmhouse Land',
    slug: 'serene-green-1-acre-farmhouse-land',
    propertyType: 'Farmhouse',
    location: 'Delhi-Jaipur Expressway, Kukas',
    address: 'Near Leela Palace Resort, Kukas, Jaipur, Rajasthan',
    price: 14500000,
    priceUnit: 'Crore',
    priceDisplay: '₹1.45 Crore',
    size: 43560,
    sizeUnit: 'sq ft',
    facing: 'East Facing',
    roadWidth: '50 ft Paved Country Road',
    status: 'Available',
    isFeatured: true,
    description: `Picturesque 1-acre private farmhouse parcel surrounded by Aravali mountain ranges and lush green organic farmlands. Features fertile sweet water borewell (250 ft), rich soil ideal for exotic orchards, organic farming, weekend retreat cottage, and resort ventures.

Fully gated and fenced with mature teak trees along boundary wall, electricity transformer installed, and private access gate.`,
    legalInformation: ['Clean Agricultural Title', 'Single Owner Registry', 'Demarcation Completed', 'No Encumbrances'],
    amenities: [
      'Sweet Water Borewell with Submersible Pump',
      'Mature Teak & Fruit Trees Bordering Property',
      'Fenced Perimeter Wall with Iron Gate',
      'Mountain Views of Aravali Ranges',
      'Independent Electricity Meter & Pole',
      'Wide Paved Approach Road'
    ],
    nearbyLandmarks: [
      'The Leela Palace Luxury Hotel - 6 mins',
      'JW Marriott Resort - 8 mins',
      'Delhi-Jaipur Expressway Highway - 5 mins',
      'Amer Fort - 18 mins'
    ],
    latitude: 27.0512,
    longitude: 75.8924,
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
    videoTitle: 'Farmhouse Aerial Drone Survey',
    images: [
      {
        url: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=1600&q=80',
        altText: 'Lush Green Farmhouse View',
        displayOrder: 0,
        isCover: true,
      },
      {
        url: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=1600&q=80',
        altText: 'Surrounding Aravali Mountains',
        displayOrder: 1,
        isCover: false,
      },
    ],
  },
];

export const initialLeads = [
  {
    name: 'Rajesh Sharma',
    phone: '+91 98290 12345',
    email: 'rajesh.sharma@example.com',
    propertyId: '',
    propertyTitle: 'Grand Vista 1200 Sq Ft Gated Township Plot',
    propertySlug: 'grand-vista-1200-sq-ft-gated-township-plot',
    budget: '₹40 - 50 Lakh',
    message: 'Interested in site visit this Saturday. Please share RERA certificate and layout plan on WhatsApp.',
    status: 'New',
    source: 'Facebook Ad',
    utmSource: 'facebook',
    utmMedium: 'paid_social',
    utmCampaign: 'jaipur_plot_fest_2026',
    utmContent: 'carousel_ad_v1',
    utmTerm: 'residential plots jaipur',
    landingPage: '/properties/grand-vista-1200-sq-ft-gated-township-plot',
    referrer: 'https://m.facebook.com/',
    notes: [
      {
        note: 'Customer saw Facebook ad carousel. Interested in 1200 sq ft plot for self-construction.',
        createdBy: 'System (Lead Form)',
        createdAt: new Date(Date.now() - 3600000 * 4),
      },
    ],
    createdAt: new Date(Date.now() - 3600000 * 4),
  },
  {
    name: 'Amit Agarwal',
    phone: '+91 94140 67890',
    email: 'amit.agarwal@example.com',
    propertyId: '',
    propertyTitle: 'Highway Touch Commercial Showroom Plot',
    propertySlug: 'highway-touch-commercial-showroom-plot',
    budget: '₹1 - 1.5 Crore',
    message: 'Looking for commercial land for opening a retail showroom. Please call back immediately.',
    status: 'Contacted',
    source: 'Instagram Ad',
    utmSource: 'instagram',
    utmMedium: 'paid_social',
    utmCampaign: 'commercial_investors_reels',
    utmContent: 'drone_video_ad',
    utmTerm: 'commercial plot tonk road',
    landingPage: '/properties/highway-touch-commercial-showroom-plot',
    referrer: 'https://www.instagram.com/',
    notes: [
      {
        note: 'Spoke with Mr. Amit. He runs an electronics chain and wants 2700 sq ft showroom plot on Tonk Road.',
        createdBy: 'Ashok Yadav',
        createdAt: new Date(Date.now() - 3600000 * 18),
      },
      {
        note: 'Sent commercial layout and FAR details on WhatsApp.',
        createdBy: 'Ashok Yadav',
        createdAt: new Date(Date.now() - 3600000 * 12),
      },
    ],
    createdAt: new Date(Date.now() - 3600000 * 20),
  },
];
